[tools]
go = "1.24.4"
"npm:commitlint" = "19.8.1"
"npm:lefthook" = "1.11.14"
"npm:prettier" = "3.5.3"

[hooks]
postinstall = "lefthook install"

[tasks.install-tools]
description = "Goのツールをインストール"
run = [
    "go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.2.2",
    "go install golang.org/x/tools/gopls@v0.19.1",
    "go install github.com/go-delve/delve/cmd/dlv@v1.25.0",
    "go install github.com/air-verse/air@v1.62.0",
]

[env]
