CREATE DATABASE IF NOT EXISTS `sample` DEFAULT CHARACTER SET utf8mb4;
USE `sample`;

SET CHARSET utf8mb4;

CREATE TABLE accounts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  balance BIGINT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
